// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ptvcewvtaxnibtboszhh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0dmNld3Z0YXhuaWJ0Ym9zemhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1OTUxMDUsImV4cCI6MjA3MzE3MTEwNX0.SOlBNt9ayKo1beWvCgE-8xxLJ-CMi99dfSsyUQ19oBk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});